/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uno;

/**
 *
 * @author w4rd0
 */
public class unoLobby extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(unoLobby.class.getName());

    /**
     * Creates new form unoHostLobby
     */
    public unoLobby() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addAI = new javax.swing.JButton();
        invite = new javax.swing.JButton();
        lobbyOptions = new javax.swing.JButton();
        back = new javax.swing.JButton();
        gameStart = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("mod2");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Active Modifiers:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 72)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UNO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 140, 90));

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("mod1");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        addAI.setText("Add AI Player");
        jPanel1.add(addAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        invite.setText("Invite Players");
        invite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviteActionPerformed(evt);
            }
        });
        jPanel1.add(invite, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        lobbyOptions.setText("Lobby Options");
        lobbyOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lobbyOptionsActionPerformed(evt);
            }
        });
        jPanel1.add(lobbyOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        gameStart.setText("Start Game");
        gameStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameStartActionPerformed(evt);
            }
        });
        jPanel1.add(gameStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Players:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        p3.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        p3.setForeground(new java.awt.Color(255, 255, 255));
        p3.setText("Player 3");
        jPanel1.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        p2.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        p2.setForeground(new java.awt.Color(255, 255, 255));
        p2.setText("Player 2");
        jPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        p4.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        p4.setForeground(new java.awt.Color(255, 255, 255));
        p4.setText("Player 4");
        jPanel1.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        p1.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        p1.setForeground(new java.awt.Color(255, 255, 255));
        p1.setText("Host");
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\w4rd0\\Downloads\\uno-1.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 420, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lobbyOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lobbyOptionsActionPerformed
unoLobOpt g = new unoLobOpt();
g.setVisible(true); 
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_lobbyOptionsActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
unoStart g = new unoStart();
g.setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void inviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviteActionPerformed
unoInvite g = new unoInvite();
g.setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_inviteActionPerformed

    private void gameStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameStartActionPerformed
unoGame g = new unoGame();
g.setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_gameStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new unoLobby().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAI;
    private javax.swing.JButton back;
    private javax.swing.JButton gameStart;
    private javax.swing.JButton invite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lobbyOptions;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    // End of variables declaration//GEN-END:variables
}
